// Hand-written wrapper — NOT generated by Fern. Safe across regeneration
// because Fern only writes to the sibling `generated/` directory.

import type { BaseClientOptions } from "../generated/BaseClient.js";
import { VoltariaClient as GeneratedVoltariaClient } from "../generated/Client.js";
import { VoltariaEnvironment } from "../generated/environments.js";

/** Thrown when an API key does not carry a recognized environment prefix. */
export class InvalidApiKeyError extends Error {
    constructor(apiKey: string) {
        const prefix = apiKey ? `${apiKey.split("_")[0]}_…` : "(empty)";
        super(
            `Invalid Voltaria API key: expected a "live_" or "sandbox_" prefix, got "${prefix}". ` +
                `Pass { environment } or { baseUrl } to route explicitly.`,
        );
        this.name = "InvalidApiKeyError";
    }
}

/**
 * Options for {@link VoltariaClient}. Same as the generated client's options,
 * minus `token` (supplied as the first positional argument).
 */
export type VoltariaClientOptions = Omit<BaseClientOptions, "token">;

/**
 * Voltaria API client.
 *
 * The base URL is derived automatically from the API key's prefix:
 *   - `live_…`    → production  (https://api.voltaria.io)
 *   - `sandbox_…` → sandbox     (https://api.sandbox.voltaria.io)
 *
 * Pass `{ environment }` or `{ baseUrl }` to override routing explicitly
 * (useful for staging or tests).
 *
 * @example
 * const voltaria = new VoltariaClient("live_…");
 * await voltaria.loans.listLoans();
 */
export class VoltariaClient extends GeneratedVoltariaClient {
    constructor(apiKey: string, options: VoltariaClientOptions = {}) {
        super({
            ...options,
            token: apiKey,
            environment: resolveEnvironment(apiKey, options),
        });
    }
}

function resolveEnvironment(
    apiKey: string,
    options: VoltariaClientOptions,
): BaseClientOptions["environment"] {
    // Explicit overrides always win.
    if (options.environment != null) return options.environment;
    if (options.baseUrl != null) return undefined;

    if (apiKey.startsWith("live_")) return VoltariaEnvironment.Production;
    if (apiKey.startsWith("sandbox_")) return VoltariaEnvironment.Sandbox;

    throw new InvalidApiKeyError(apiKey);
}
